power <- read.csv2("household_power_consumption.txt",header = TRUE, stringsAsFactors = FALSE)
str(power)
powerSelect = subset(power, Date == "1/2/2007" | Date == "2/2/2007")
powerSelect$Date <- as.Date(powerSelect$Date, format = "%d/%m/%Y")
str(powerSelect)
x = paste(powerSelect$Date, powerSelect$Time)
powerSelect$Datetime <- strptime(x, format = "%Y-%m-%d %H:%M:%S")
powerSelect$Global_active_power <- as.numeric(powerSelect$Global_active_power)
powerSelect$Global_reactive_power <- as.numeric(powerSelect$Global_reactive_power)
powerSelect$Voltage <- as.numeric(powerSelect$Voltage)
powerSelect$Global_intensity <- as.numeric(powerSelect$Global_intensity)
powerSelect$Global_Sub_metering_1 <- as.numeric(powerSelect$Sub_metering_1)
powerSelect$Global_Sub_metering_2 <- as.numeric(powerSelect$Sub_metering_2)
powerSelect$Global_Sub_metering_3 <- as.numeric(powerSelect$Sub_metering_3)
str(powerSelect)