par(mfrow = c(2,2))
plot(powerSelect$Datetime, powerSelect$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
plot(powerSelect$Datetime, powerSelect$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(powerSelect$Datetime, powerSelect$Global_Sub_metering_1, type = "l" ,ylab = "Energy sub metering", xlab = "")
lines(powerSelect$Datetime, powerSelect$Global_Sub_metering_2, col = "red")
lines(powerSelect$Datetime, powerSelect$Global_Sub_metering_3, col = "blue")
legend('topright', c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, bty='n', cex = 0.8)
plot(powerSelect$Datetime, powerSelect$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.copy(png, "plot4.png")
dev.off()