plot(powerSelect$Datetime, powerSelect$Global_Sub_metering_1, type = "l" ,ylab = "Energy sub metering", xlab = "")
lines(powerSelect$Datetime, powerSelect$Global_Sub_metering_2, col = "red")
lines(powerSelect$Datetime, powerSelect$Global_Sub_metering_3, col = "blue")
legend('topright', c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, cex = 0.8)
dev.copy(png, "plot3.png")
dev.off()